import { reqHandler } from '../dist/money-transfers/server/server.mjs';

/**
 * Vercel serverless function entrypoint for Angular SSR.
 * Delegates handling to the Express-based request handler generated by Angular.
 */
export default function handler(req, res) {
  return reqHandler(req, res);
}


